# Generated by Django 5.2 on 2025-05-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='count_of_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
