# Generated by Django 4.2.2 on 2025-06-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_count_of_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['title', 'created_at'], 'permissions': [('can_edit_articles', 'Can edit articles')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
